server/Controllers/MealController.cs
using Microsoft.AspNet.Identity;
using server.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;


namespace server.Controllers
{
    [Authorize]
    public class MealController : ApiController
    {

        private readonly ApplicationDbContext _context;


        public MealController()
        {
            _context = new ApplicationDbContext();
        }
        // GET api/<controller>
        public IHttpActionResult Get()
        {
            var meals = _context.meals.ToList();
            if(meals == null || meals.Count == 0)
            {
                return NotFound();
            }
            return (IHttpActionResult)Ok(meals);
        }


        // GET api/<controller>/5
        public IHttpActionResult Get(int id)
        {
            var meals_Id = _context.meals.FirstOrDefault(a => a.Id == id);
            if (meals_Id == null)
            {
                return NotFound();
            }
            return (IHttpActionResult)Ok(meals_Id);
        }

        // POST api/<controller>
        public IHttpActionResult Post(MealBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            if(_context.meals.FirstOrDefault(a => a.Id == model.Id) != null)
            {
                return BadRequest();
            }
            var New_meal = new Meal() {
                AmountLeft = model.AmountLeft,
                Price = model.Price,
                Name = model.Name,
                ImageURL = model.ImageURL,
                Type = model.Type,
            };
            _context.meals.Add(New_meal);
            _context.SaveChanges();
            return Ok("Has Save");
        }
        // POST api/<controller>/id
        public IHttpActionResult Post(int id, MealEditBlindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var EditMeal = _context.meals.FirstOrDefault(a => a.Id == id);
            if ( EditMeal == null)
            {
                return BadRequest();
            }
            EditMeal.AmountLeft = model.AmountLeft;
            EditMeal.Price = model.Price;
            EditMeal.Name = model.Name;
            EditMeal.ImageURL = model.ImageURL;
            EditMeal.Type = model.Type;
            _context.meals.AddOrUpdate(EditMeal);
            _context.SaveChanges();
            return Ok("Has Save");
        }
        // PUT api/<controller>

        // DELETE api/<controller>/5
        public IHttpActionResult Delete(int id)
        {
            var DeleteMeal = _context.meals.FirstOrDefault(a => a.Id == id);
            if (DeleteMeal == null)
            {
                return BadRequest();
            }
            _context.meals.Remove(DeleteMeal);
            _context.SaveChanges();
            return Ok("Has Save");
        }
    }
}

server/Controllers/MealsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using server.Models;

namespace server.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class MealsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Meals
        public ActionResult Index(string searchString)
        {

            var meals = from m in db.Meals select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                meals = meals.Where(s => s.Type.Contains(searchString));
            }

            return View(meals.ToList());
        }
        // GET: Meals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // GET: Meals/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Meals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Meal meal)
        {
            if (ModelState.IsValid)
            {
                db.Meals.Add(meal);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(meal);
        }

        // GET: Meals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Meal meal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(meal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(meal);
        }

        // GET: Meals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meal meal = db.Meals.Find(id);
            if (meal == null)
            {
                return HttpNotFound();
            }
            return View(meal);
        }

        // POST: Meals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Meal meal = db.Meals.Find(id);
            db.Meals.Remove(meal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }
    }
}

server/Controllers/api/MealController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using server.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace server.Controllers.api
{
    [Authorize]
    public class MealController : ApiController
    {

        private readonly ApplicationDbContext _context;


        public MealController()
        {
            _context = new ApplicationDbContext();
        }

        // GET api/<controller>
        [AllowAnonymous]
        public IHttpActionResult Get()
        {
            var meals = _context.meals.ToList();
            if(meals == null || meals.Count == 0)
            {
                return NotFound();
            }
            return Ok(meals);
        }


        // GET api/<controller>/5
        [AllowAnonymous]
        public IHttpActionResult Get(int id)
        {
            var meals_Id = _context.meals.FirstOrDefault(a => a.Id == id);
            if (meals_Id == null)
            {
                return NotFound();
            }
            return Ok(meals_Id);
        }

        [AllowAnonymous]
        [HttpGet]
        public IEnumerable<Meal> GetMeal([FromUri] PagingParameterModel pagingparametermodel)
        {
            // Return List of Customer  
            var source = (from meal in _context.meals.
                            OrderBy(a => a.Id)
                          select meal).AsQueryable();
            int count = source.Count();

            // Parameter is passed from Query string if it is null then it default Value will be pageNumber:1  
            int CurrentPage = pagingparametermodel.pageNumber;

            // Parameter is passed from Query string if it is null then it default Value will be pageSize:20  
            int PageSize = pagingparametermodel.pageSize;

            // Display TotalCount to Records to User  
            int TotalCount = count;

            // Calculating Totalpage by Dividing (No of Records / Pagesize)  
            int TotalPages = (int)Math.Ceiling(count / (double)PageSize);

            // Returns List of Customer after applying Paging   
            var items = source.Skip((CurrentPage - 1) * PageSize).Take(PageSize).ToList();

            // if CurrentPage is greater than 1 means it has previousPage  
            var previousPage = CurrentPage > 1 ? "Yes" : "No";

            // if TotalPages is greater than CurrentPage means it has nextPage  
            var nextPage = CurrentPage < TotalPages ? "Yes" : "No";

            // Object which we are going to send in header   
            var paginationMetadata = new
            {
                totalCount = TotalCount,
                pageSize = PageSize,
                currentPage = CurrentPage,
                totalPages = TotalPages,
                previousPage,
                nextPage
            };

            // Setting Header  
            HttpContext.Current.Response.Headers.Add("Paging-Headers", JsonConvert.SerializeObject(paginationMetadata));
            // Returing List of Customers Collections  
            return items;
        }

        // POST api/<controller>
        [Authorize(Roles = "Admin, Manager")]
        public IHttpActionResult Post(MealBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            if(_context.meals.FirstOrDefault(a => a.Id == model.Id) != null)
            {
                return BadRequest();
            }
            var New_meal = new Meal() {
                AmountLeft = model.AmountLeft,
                Price = model.Price,
                Name = model.Name,
                ImageURL = model.ImageURL,
                Type = model.Type,
            };
            _context.meals.Add(New_meal);
            _context.SaveChanges();
            return Ok("Has Save");
        }
        // POST api/<controller>/id
        [Authorize(Roles = "Admin, Manager")]
        public IHttpActionResult Post(int id, MealEditBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var EditMeal = _context.meals.FirstOrDefault(a => a.Id == id);
            if ( EditMeal == null)
            {
                return BadRequest();
            }
            EditMeal.AmountLeft = model.AmountLeft;
            EditMeal.Price = model.Price;
            EditMeal.Name = model.Name;
            EditMeal.ImageURL = model.ImageURL;
            EditMeal.Type = model.Type;
            _context.meals.AddOrUpdate(EditMeal);
            _context.SaveChanges();
            return Ok("Has Save");
        }

        // PUT api/<controller>

        // DELETE api/<controller>/5
        [Authorize(Roles = "Admin, Manager")]
        public IHttpActionResult Delete(int id)
        {
            var DeleteMeal = _context.meals.FirstOrDefault(a => a.Id == id);
            if (DeleteMeal == null)
            {
                return BadRequest();
            }
            _context.meals.Remove(DeleteMeal);
            _context.SaveChanges();
            return Ok("Has Save");
        }
    }
}

server/Controllers/api/MealsController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using server.Models;
using server.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http;

namespace server.Controllers.api
{
    [Authorize]
    public class MealsController : ApiController
    {
        private readonly ApplicationDbContext _context;


        public MealsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET api/<controller>/5
        [AllowAnonymous]
        public IHttpActionResult Get(int id)
        {
            var meals_Id = _context.Meals.FirstOrDefault(a => a.Id == id);
            if (meals_Id == null)
            {
                return NotFound();
            }
            var viewMeals = MealViewModel.FromMeal(meals_Id);          
            return Ok(viewMeals);
        }

        // GET api/<controller>
        [AllowAnonymous]
        [HttpGet]
        public PagingResult Get([FromUri] PagingParameterModel pagingparametermodel)
        {
            // Return List of Customer  
            var Meals = _context.Meals.ToList();
            List<MealViewModel> source = new List<MealViewModel>();
            foreach (var o in Meals)
            {
                source.Add(MealViewModel.FromMeal(o));
            }
            int count = source.Count();

            // Parameter is passed from Query string if it is null then it default Value will be pageNumber:1  
            int CurrentPage = pagingparametermodel.pageNumber;

            // Parameter is passed from Query string if it is null then it default Value will be pageSize:20  
            int PageSize = pagingparametermodel.pageSize;

            // Display TotalCount to Records to User  
            int TotalCount = count;

            // Calculating Totalpage by Dividing (No of Records / Pagesize)  
            int TotalPages = (int)Math.Ceiling(count / (double)PageSize);

            // Returns List of Customer after applying Paging   
            var items = source.Skip((CurrentPage - 1) * PageSize).Take(PageSize).ToList();

            // if CurrentPage is greater than 1 means it has previousPage  
            bool previousPage = CurrentPage > 1;

            // if TotalPages is greater than CurrentPage means it has nextPage  
            bool nextPage = CurrentPage < TotalPages;

            // Object which we are going to send in header   
            PagingResult returnData = new PagingResult
            {
                totalCount = TotalCount,
                pageSize = PageSize,
                currentPage = CurrentPage,
                totalPages = TotalPages,
                previousPage = previousPage,
                nextPage = nextPage,
                items = items,
            };

            // Returing List of Customers Collections  
            return returnData;
        }

        // POST api/<controller>
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        public IHttpActionResult Create(CreateMealBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            if (_context.Meals.FirstOrDefault(a => a.Id == model.Id) != null)
            {
                return BadRequest();
            }
            var New_meal = new Meal()
            {
                AmountLeft = model.AmountLeft,
                Price = model.Price,
                Name = model.Name,
                ImageURL = model.ImageURL,
                Type = model.Type,
            };
            _context.Meals.Add(New_meal);
            _context.SaveChanges();
            return Ok("Saved");
        }
        // POST api/<controller>/id
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        public IHttpActionResult Update(int id, EditMealBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var EditMeal = _context.Meals.FirstOrDefault(a => a.Id == id);
            if (EditMeal == null)
            {
                return BadRequest();
            }
            EditMeal.AmountLeft = model.AmountLeft;
            EditMeal.Price = model.Price;
            EditMeal.Name = model.Name;
            EditMeal.ImageURL = model.ImageURL;
            EditMeal.Type = model.Type;
            _context.Meals.AddOrUpdate(EditMeal);
            _context.SaveChanges();
            return Ok("Saved");
        }

        // PUT api/<controller>

        // DELETE api/<controller>/5
        [Authorize(Roles = "Admin, Manager")]
        public IHttpActionResult Delete(int id)
        {
            var DeleteMeal = _context.Meals.FirstOrDefault(a => a.Id == id);
            if (DeleteMeal == null)
            {
                return BadRequest();
            }
            _context.Meals.Remove(DeleteMeal);
            _context.SaveChanges();
            return Ok("Saved");
        }
    }
}

server/Views/Meals/Create.cshtml
@model server.Models.Meal


@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Meal</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmountLeft, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmountLeft, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmountLeft, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                   style="display:none;" />
            <input type="button" id="btnUpload" value="Choose" class="btn btn-outline-dark" />
            <img id="pictureUpload" />
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Type,
                                 new List<SelectListItem>()
                                 {
                                    new SelectListItem() { Text = "Dish", Value = "dish" },
                                    new SelectListItem() { Text = "Drink", Value = "drink" }
                                 },
                                 new { htmlAttributes = new { @class = "form-control" } }
                               )
        </div>
    </div>
    <div class="form-group">
        <br />
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section upload
{
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });
        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);

                $.ajax(
                    {
                        type: 'POST',
                        url: '/Meals/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {

                            $('#pictureUpload').attr('src', urlImage);
                            $('#ImageURL').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}

server/Views/Meals/Delete.cshtml
@model server.Models.Meal

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountLeft)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountLeft)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

server/Views/Meals/Details.cshtml
@model server.Models.Meal

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountLeft)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountLeft)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <p>@Html.DisplayFor(model => model.ImageURL)</p>
            <img src="@Html.DisplayFor(model => model.ImageURL)" style="max-width: 500px"  />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

server/Views/Meals/Edit.cshtml
@model server.Models.Meal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Meal</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmountLeft, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmountLeft, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmountLeft, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
                   style="display:none;" />
            <input type="button" id="btnUpload" value="Choose" class="btn btn-outline-dark" />
            <img src="@Model.ImageURL" id="pictureUpload" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Type,
                                 new List<SelectListItem>()
                                 {
                                    new SelectListItem() { Text = "Dish", Value = "dish" },
                                    new SelectListItem() { Text = "Drink", Value = "drink" }
                                 },
                                 new { htmlAttributes = new { @class = "form-control" } }
                               )
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section upload
{
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });
        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);

                $.ajax(
                    {
                        type: 'POST',
                        url: '/Meals/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {

                            $('#pictureUpload').attr('src', urlImage);
                            $('#ImageURL').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}

server/Views/Meals/Index.cshtml
@model IEnumerable<server.Models.Meal>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Meals</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountLeft)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        <th>
            @using (Html.BeginForm("Index", "Meals", FormMethod.Get))
            {

                <p>

                    @Html.DropDownList("searchString", new List<SelectListItem>
             {
               new SelectListItem{ Text="Dish", Value = "dish" },
               new SelectListItem{ Text="Drink", Value = "drink" },

             }, "Type", ViewBag.CurrentTypes as string)
                    <input type="submit" value="Search" />


                </p>
            }
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountLeft)
            </td>
            <td>
                <img src="@Html.DisplayFor(modelItem => item.ImageURL)" width="200" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>